// ═══════════════════════════════════════════════════════════
//  API — communication avec Back4App
// ═══════════════════════════════════════════════════════════

const HEADERS = {
    "X-Parse-Application-Id": CONFIG.APP_ID,
    "X-Parse-REST-API-Key":   CONFIG.REST_API_KEY,
    "Content-Type":           "application/json",
};

function authHeaders(sessionToken) {
    const h = { ...HEADERS };
    if (sessionToken) h["X-Parse-Session-Token"] = sessionToken;
    return h;
}

async function apiCall(method, path, body = null, sessionToken = null) {
    const options = {
        method,
        headers: authHeaders(sessionToken),
    };
    if (body) options.body = JSON.stringify(body);
    const res = await fetch(CONFIG.API_URL + path, options);
    return { status: res.status, data: await res.json() };
}

// ── Auth ────────────────────────────────────────────────────
async function login(username, password) {
    const res = await fetch(
        `${CONFIG.API_URL}/login?username=${encodeURIComponent(username)}&password=${encodeURIComponent(password)}`,
        { method: "GET", headers: HEADERS }
    );
    if (res.status === 200) return await res.json();
    return null;
}

async function register(username, password, fullName, salle, horaire) {
    const { status, data } = await apiCall("POST", "/users", {
        username, password, fullName,
        classe:  `${salle} — ${horaire}`,
        salle, horaire,
        role: "etudiant",
    });
    return status === 201 ? data : null;
}

async function changePassword(objectId, newPassword, sessionToken) {
    const { status } = await apiCall("PUT", `/users/${objectId}`, { password: newPassword }, sessionToken);
    return status === 200;
}

// ── Tâches ──────────────────────────────────────────────────
async function getAllTasks() {
    const { data } = await apiCall("GET", "/classes/Task?order=-createdAt&limit=200");
    const tasks = data.results || [];
    const prof    = tasks.filter(t => t.autoGenerated !== true);
    const student = tasks.filter(t => t.autoGenerated === true);
    return [...prof, ...student];
}

async function createTask(title, description) {
    const { status } = await apiCall("POST", "/classes/Task", {
        title, description, autoGenerated: false
    });
    return status === 201;
}

async function createTaskForPublication(studentName, networkName, link) {
    const { status } = await apiCall("POST", "/classes/Task", {
        title:           `Liker/commenter le ${networkName} de ${studentName}`,
        description:     link,
        autoGenerated:   true,
        studentName,
        network:         networkName,
        publicationLink: link,
    });
    return status === 201;
}

async function deleteTask(taskId) {
    const { status } = await apiCall("DELETE", `/classes/Task/${taskId}`);
    return status === 200;
}

// ── Soumissions ──────────────────────────────────────────────
async function getAllSubmissions() {
    const { data } = await apiCall("GET", "/classes/Submission?include=task,student&limit=500");
    return data.results || [];
}

async function getSubmissionsByStudent(studentId) {
    const where = encodeURIComponent(JSON.stringify({
        student: { "__type": "Pointer", "className": "_User", "objectId": studentId }
    }));
    const { data } = await apiCall("GET", `/classes/Submission?where=${where}&include=task&limit=200`);
    return data.results || [];
}

async function submitTask(studentId, taskId, proofLink, commentUsed, sessionToken) {
    const { status } = await apiCall("POST", "/classes/Submission", {
        student:     { "__type": "Pointer", "className": "_User", "objectId": studentId },
        task:        { "__type": "Pointer", "className": "Task",  "objectId": taskId },
        status:      "terminé",
        proofLink,
        commentUsed,
    }, sessionToken);
    return status === 201;
}

// ── Étudiants ────────────────────────────────────────────────
async function getAllStudents() {
    const where = encodeURIComponent(JSON.stringify({ role: "etudiant" }));
    const { data } = await apiCall("GET", `/classes/_User?where=${where}&limit=200`);
    return data.results || [];
}

async function updateUser(objectId, data, sessionToken) {
    const { status } = await apiCall("PUT", `/users/${objectId}`, data, sessionToken);
    return status === 200;
}

// ── Commentaires ─────────────────────────────────────────────
async function getPresetComments() {
    const { data } = await apiCall("GET", "/classes/PresetComment");
    return data.results || [];
}
